name:                what2wear-server
version:             0.1.0
github:              "Plenglin/what2wear"
license:             AGPL-3.0-only
author:              Astrid Yu
maintainer:          astrid@astrid.tech
copyright:           2020 Astrid Yu

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Plenglin/what2wear#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- yesod
- dotenv

library:
  source-dirs: src

executables:
  what2wear-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - what2wear-server

tests:
  what2wear-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - what2wear-server
